[project]
name = "project-8-create-a-python-streamlit-bmi-calculator-web-app-in-just-6-minutes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.44.1",
]
