[project]
name = "project-9-build-a-python-website-in-15-minutes-with-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "streamlit>=1.44.1",
]
